# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppodealTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppodealTest
    pod 'APDAdColonyAdapter', '2.11.1.3'
    pod 'APDAmazonAdsAdapter', '2.11.1.2'
    pod 'APDAppLovinAdapter', '2.11.1.3'
    pod 'APDBidMachineAdapter', '2.11.1.3' # Required
    pod 'APDFacebookAudienceAdapter', '2.11.1.2'
    pod 'APDIronSourceAdapter', '2.11.1.3'
    pod 'APDMyTargetAdapter', '2.11.1.2'
    pod 'APDOguryAdapter', '2.11.1.1'
    pod 'APDUnityAdapter', '2.11.1.2'
    pod 'APDVungleAdapter', '2.11.1.2'
    pod 'APDYandexAdapter', '2.11.1.1'

end
